<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>MVF.Demo</RootNamespace>
        <UseWPF>true</UseWPF>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MVF" Version="0.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="src\UI\HTML\**\*.*">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="src\UI\HTML\Components\" />
      <Folder Include="src\UI\HTML\Widgets\" />
      <Folder Include="src\UI\View\Components\" />
      <Folder Include="src\UI\View\Widgets\" />
    </ItemGroup>

</Project>
