<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWPF>true</UseWPF>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="src\" />
      <Folder Include="src\UI\Frame\" />
      <Folder Include="src\UI\JS\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="src\UI\View\Canvas\MVFViewCanvas.html" LogicalName="MVF.UI.View.Canvas.MVFViewCanvas.html" />
      <EmbeddedResource Include="src\UI\View\Canvas\MVFViewCanvas.css" LogicalName="MVF.UI.View.Canvas.MVFViewCanvas.css" />
      <EmbeddedResource Include="src\UI\JS\MVFViewCanvasDom.js" LogicalName="MVF.UI.JS.MVFViewCanvasDom.js" />
    </ItemGroup>

</Project>
